### ISSUE TITLE
application.log file is created when importing classes from Models.py

### ISSUE THREAD

**Issue by plgregoire** [Accenture/AmpliGraph#103]
### Description

When importing models, a file named application.log is created in the project.

`from ampligraph.latent_features import ComplEx, TransE, DistMult, HolE`

The reason is that models.py contains logging instructions that are outside of classes. 

```
import numpy as np
import tensorflow as tf
from sklearn.utils import check_random_state
import abc
from tqdm import tqdm
import logging

MODEL_REGISTRY = {}

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

from .loss_functions import LOSS_REGISTRY
```
Since those instructions are executed during the importation step, it creates a file before we can have the chance to configure the logging mechanism. 

I would suggest to put those instructions at the beginning of the constructor of the class EmbeddingModel to fix the issue

**Comment by plgregoire** [comment]
Adding a configuration file declaring the logger allowed us to catch the logs with our custom handler 

```
loggers:
    ampligraph.evaluation.protocol:
        level: DEBUG
        propagate: yes
```

**Comment by diskun00** [comment]
> Adding a configuration file declaring the logger allowed us to catch the logs with our custom handler
> 
> ```
> loggers:
>     ampligraph.evaluation.protocol:
>         level: DEBUG
>         propagate: yes
> ```

Hi @plgregoire, I tried to config the logger in the conf file, but it seems the application.log is still created. Have you found a solution to prevent its creation?

**Comment by Hamsaask** [comment]
> > Adding a configuration file declaring the logger allowed us to catch the logs with our custom handler
> > ```
> > loggers:
> >     ampligraph.evaluation.protocol:
> >         level: DEBUG
> >         propagate: yes
> > ```
> 
> Hi @plgregoire, I tried to config the logger in the conf file, but it seems the application.log is still created. Have you found a solution to prevent its creation?

Hi @diskun00 , I was working with ampligraphs and encountered the same problem while deploying it. Have you found a solution to prevent the creation of application.log
