### ISSUE TITLE
Is it possible to get first k entities for query (h,r,?)

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [Accenture/AmpliGraph#118]
Hello,

I was wondering is there a way to get the first k entities(and associated score) that give the top k highest score for the query like (h, r, ?) or (?, r, t). This would be quite helpful to understand the behavior of the model.

Right now given (h,r,t) the library can compute the rank of h/t for query (?, r, t)/(h, r, ?).

**Comment by NicholasMcCarthy** [comment]
Hi @Chen-Cai-OSU, 

Great suggestion! I've been working on a knowledge discovery API and have a need for a similar function, so: yes, I'll implement something like this into a high-level function.

In the mean time, the following snippet should get the job done (for the <h, r, ?> case at any rate, the rest is left as an exercise for the reader ;-) ):

```
hr = X[0,0:2] # np.array 
top_k = 15

C = np.array([np.append(hr, x) for x in list(model.ent_to_idx.keys())])

results = pd.DataFrame(np.hstack([C, model.predict(C)]), columns=['head', 'relation', 'tail', 'score'])

results.sort_values('score', ascending=False, inplace=True)

print(results[:top_k])
```

**Comment by Chen-Cai-OSU** [comment]
Thanks for your code. This works like a charm and is exactly what I want!
