### ISSUE TITLE
Ordering of ranks in evaluate_performance is different from documentation

### ISSUE THREAD

**Issue by dogatekin** [Accenture/AmpliGraph#126]
#### Background and Context
When evaluating the performance of a model with the default protocol, AmpliGraph returns two ranks for each test sample: one ranking among its subject corruptions and another one among its object corruptions. The ordering of these rankings is different from the one stated in the documentation.

#### Description
The documentation for [`evaluate_performance`](https://docs.ampligraph.org/en/1.0.3/generated/ampligraph.evaluation.evaluate_performance.html#evaluate-performance) states:

> When `use_default_protocol=True` or `corrupt_side='s+o'`, the function returns 2*n ranks instead of n. In that case the first n elements of ranks are obtained against subject corruptions. From n+1 until 2n ranks are obtained against object corruptions.
    
However, when I use the function in this way I get the ranks in the following format: 
    
[rank of first element against its subject corruptions, 
rank of first element against its object corruptions, 
rank of second element against its subject corruptions, 
rank of second element against its object corruptions, @
.
.
. ]
    
This can also be seen in the code [here](https://github.com/Accenture/AmpliGraph/blob/master/ampligraph/evaluation/protocol.py#L623).

**Comment by sumitpai** [comment]
Hi @dogatekin. You are right. We will update the docs. In the next release the ranks would be returned as (N, n_sides).

**Comment by lukostaz** [comment]
Fixed in `6dd2c7ff92f1f1df3f68fc8d1ba58406c95ffd40` when merging #56 .
