### ISSUE TITLE
RandomBaseline does not filter out triples during performance evaluation

### ISSUE THREAD

**Issue by dogatekin** [Accenture/AmpliGraph#133]
### Description
The RandomBaseline model does not filter out the known positive triples when its performance is being evaluated.

### Actual Behavior
The triples given to the `filter_triples` argument of `evaluate_performance` are ignored if the model is RandomBaseline.

### Expected Behavior
The triples given to the `filter_triples` argument of `evaluate_performance` should be filtered out before calculating the ranks, regardless of the model.

### Steps to Reproduce
A small example to demonstrate:
```python
import numpy as np
from ampligraph.datasets import load_fb15k_237
from ampligraph.latent_features import RandomBaseline
from ampligraph.evaluation import evaluate_performance

X = load_fb15k_237()

model = RandomBaseline()
model.fit(X['train'])

unfiltered_ranks = evaluate_performance(X['test'], model)

model.rnd.seed(0)  # Reset random state
filtered_ranks = evaluate_performance(X['test'], model, 
                                      filter_triples=np.concatenate((X['train'], X['test'])))

np.array_equal(unfiltered_ranks, filtered_ranks)  # Returns True
```

### Source
The [`get_ranks`](https://github.com/Accenture/AmpliGraph/blob/master/ampligraph/latent_features/models.py#L1626) function of RandomBaseline is different from that of the other models, it doesn't go through the filtering process.

**Comment by tabacof** [comment]
Solved by #140.
