### ISSUE TITLE
Simplify DatasetAdapter class and usage

### ISSUE THREAD

**Issue by NicholasMcCarthy** [Accenture/AmpliGraph#141]
**Background and Context**

The DatasetAdapter classes and usage in EmbeddingModel can be simplified significantly, broken down into two related issues below.

**Description**

### Issue 1

```EmbeddingModel.__init__ ``` 

has:
```
        self.eval_dataset_handle = None
        self.train_dataset_handle = None
```

However, in many cases the usage for eval_dataset_handle is:

```
	self.eval_dataset_handle = self.train_dataset_handle
```
or assigned to a newly created DatasetAdapter class, as in the case with ```EmbeddingModel.predict()```: 
```
	dataset_handle = NumpyDatasetAdapter()  
	dataset_handle.use_mappings(self.rel_to_idx, self.ent_to_idx)  
	dataset_handle.set_data(X, "test", mapped_status=from_idx)  
	  
	self.eval_dataset_handle = dataset_handle
```

As there is already a distinction between datasets using the ```dataset_type``` or ```mode``` parameter I think this can be simplified to a single ```self.dataset_handle``` for each model. 

Selecting the evaluation/prediction dataset can still work by using (for example):

```
	self.dataset_handle.set_data(X['test'], 'predict')  # or test   
```

### Issue 2

```NumpyDatasetAdapter``` 

has functions:

```
	def get_next_train_batch(self, batch_size=1, dataset_type="train"):
		...		
	def get_next_eval_batch(self, batch_size=1, dataset_type="test"):
		...
	def get_next_batch_with_filter(self, batch_size=1, dataset_type="test"):
		...
```

In which case, in conjunction with the issue above the following lines do the exact same thing:

```
	self.train_dataset_handle.get_next_eval_batch(batch_size=1, dataset_type='valid') 

	self.eval_dataset_handle.get_next_train_batch(batch_size=1, dataset_type='valid')
```

Obviously this should not really be a problem when implementing code, but is I think needlessly complex. 

## Proposed Fixes

1. Refactor ```train_dataset_handle``` and ```eval_dataset_handle``` to ```dataset_handle``` in ```EmbeddingModel``` - making sure to manage the cleanup, graph switching, etc.

2. Implement:

```
	def get_batch(self, dataset_type, batch_size=1, use_filter=False):
		...
```

to replace the three existing batch functions.

**Comment by NicholasMcCarthy** [comment]
@sumitpai I think I'm right here but it's based on my experience of implementing the conve & conve_adapter classes - if there's a potential issue with the fixes due to the standard filtering you should have a better idea than me.

**Comment by sumitpai** [comment]
#150 closes this.
