### ISSUE TITLE
Test suite on the GPU

### ISSUE THREAD

**Issue by tabacof** [Accenture/AmpliGraph#144]
**Background and Context**
Currently both of our test suites (CircleCI and Jenkins) run on the CPU. However, some bugs such as #137 are GPU only, so our continuous integration is blind to those issues right now. 

**Description**
Have either one of the test suites run on the GPU or create a new one on the GPU, whichever is easier.

**Comment by chanlevan** [comment]
Jenkins Test suite is now working on GPU. The script is dynamic enough to check if any GPU is available to run the tests on it.
