### ISSUE TITLE
Optimize large graph evaluation mode when custom corruptions are used(from a limited set)

### ISSUE THREAD

**Issue by sumitpai** [Accenture/AmpliGraph#162]
**Background and Context**
With s+o and all corruptions, we cant load all the embeddings in the memory. But when we go for a custom evaluation, we may be able to load the embeddings of the test triples and all the corruptions from custom set in memory.
**Description**
perform a check to see if all the required embeddings can be held in memory and load selectively - and perform evaluation in regular mode to improve speed

**Comment by lukostaz** [comment]
Can this be included in 1.3?

**Comment by lukostaz** [comment]
This does not apply anymore to the current codebase. Closing it.
