### ISSUE TITLE
ValueError: Loss is inf. Please change the hyperparameters

### ISSUE THREAD

**Issue by SRHyd** [Accenture/AmpliGraph#164]
Hello,

I have a large dataset with triples size as follows.
Train set size:  (52016485, 3)
Test set size:  (10000, 3)

After training 7 epochs, I get the following error.
Average Loss:   0.621298:   at 7/300 epochs
ERROR - Loss is inf. Please change the hyperparameters.

I initialize the model with following settings.

batches_count = 6985        # Approx. 7500 triples per batch
model = ComplEx(batches_count=batches_count,
                epochs=300,
                k=100,
                eta=20,
                optimizer='adam', 
                optimizer_params={'lr':1e-4},
                loss='multiclass_nll',
                regularizer='LP', 
                regularizer_params={'p':3, 'lambda':1e-5}, 
                seed=0, 
                verbose=True)

How to solve this error? please help?

Thank you,
SR

**Comment by sumitpai** [comment]
You could try to increase lambda (regularisation weight) to say 1e-2 or 1e-3 and/or reduce the learning rate to 5e-5 or 1e-5

**Comment by sumitpai** [comment]
You could also try using a different loss like self_adversarial or pairwise loss

**Comment by surenreddy** [comment]
> You could try to increase lambda (regularisation weight) to say 1e-2 or 1e-3 and/or reduce the learning rate to 5e-5 or 1e-5

Tried the above learning rate and regularisation but no difference.

**Comment by surenreddy** [comment]
> You could also try using a different loss like self_adversarial or pairwise loss

changing the loss from 'multiclass_nll' to 'self_adversarial' solved the problem!
Thank you @sumitpai
