### ISSUE TITLE
Problem reloading ConvKB models when "dealing_with_large_graphs"

### ISSUE THREAD

**Issue by jharlacher** [Accenture/AmpliGraph#172]
I can train a ConvKB model in the dealing_with_large_graphs case, but when I try to reload it using restore_model and run "predict" it says ent_emb is missing from the object.

ConvKB.py overrides _load_model_from_trained_params and when dealing with large graphs does not set ent_emb, only sets ent_emb_cpu. 

If I change ConvKB.py to set ent_emb to zero after setting ent_emb_cpu then "predict" runs. It's set to zero in the same way as in the base class.

**Comment by NicholasMcCarthy** [comment]
Hi @jharlacher,

Thanks for the bug report. Have just fixed the issue and it will be merged into develop branch shortly.
