### ISSUE TITLE
Loss is nan after first epoch when training ConvE

### ISSUE THREAD

**Issue by alexdevmotion** [Accenture/AmpliGraph#192]
### Description
Trying to train a ConvE model with basically any hyperparameters (I tried many combinations: leaving the default ones, the ones from the Performance page and variations of them)

### Actual Behavior
generates the following error
```
Average Loss: 122.950927:  10%|█         | 1/10 [00:21<03:15, 21.75s/epoch]ERROR - Loss is nan. Please change the hyperparameters.
Traceback (most recent call last):
...
  File "...\train_ampligraph.py", line 198, in do_train
    model.fit(train)
  File "...\ampligraph\latent_features\models\ConvE.py", line 737, in fit
    raise e
  File "...\ampligraph\latent_features\models\ConvE.py", line 710, in fit
    raise ValueError(msg)
ValueError: Loss is nan. Please change the hyperparameters.
Average Loss: 122.950927:  10%|█         | 1/10 [00:21<03:17, 22.00s/epoch]
```

### Expected Behavior
no error

### Steps to Reproduce
```
params = {
            'batches_count': 500,
            'epochs': 10,
            'k': 200,
            ... any other hyperparam combinations ...
}
model = ConvE(**params)
model.fit(any_train_data)
```
```
>>> ampligraph.__version__
'1.3.1'
```
```
>>> sys.version
'3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:18:16) [MSC v.1916 64 bit (AMD64)]'
```
```
>>> tensorflow.__version__
'1.13.1'
```

Back when I reported #189 I was able to train the model, but not able to evaluate it. Now I'm not able to train it anymore.
Am I doing something wrong?

**Comment by NicholasMcCarthy** [comment]
Hi @alexdevmotion,

The only changes to the ConvE/EmbeddingModel codebase since issue #189 were [a minor fix to select the correct default evaluation protocol](https://github.com/Accenture/AmpliGraph/commit/c5d5775f7d6e7790016ab04f5672cafa17b82734)  and fixing some flake8 lint errors in the BCE loss function. 

Are you using one of the standard datasets or your own one? And if it's your own one, is it the exact same as before?

**Comment by NicholasMcCarthy** [comment]
ConvE passes all tests with the default hyper-parameters and datasets, and otherwise appears to function normally so closing this issue.
