### ISSUE TITLE
tensorflow 2 in tutorials

### ISSUE THREAD

**Issue by rschmaelzle** [Accenture/AmpliGraph#197]
### Description
tensorflow.contrib not in >tf2, but that seems now standard in googlcolab, therefore error is thrown during import of ComplEx

### Suggested solution
change notebook to !pip install "tensorflow-gpu>=1.14.0,<2.0"

**Comment by chanlevan** [comment]
@rschmaelzle if you take a look in the landing page of the repo, there is a clear requirement of specifying tensorflow < version 2. 
<img width="559" alt="Screenshot 2020-05-17 at 09 52 55" src="https://user-images.githubusercontent.com/11374111/82139992-385bb400-9824-11ea-8d5b-3fb9a8b8a014.png">
At the moment Ampligraph is not supporting tensorflow 2 yet, but this is a plan in the near future.

**Comment by rschmaelzle** [comment]
thanks! sorry! (just thought I'd note because per default, it seems that googlecollab is now running tf>2). Best r

**Comment by lukostaz** [comment]
Thanks @rschmaelzle , good point. Indeed, colab switched to tf2 a couple of months ago but we did not update our tutorial. We'll update as suggested. 
p.s. we are working on a tf2 porting which will be out soon.
