### ISSUE TITLE
Limit the number of threads used when fitting a model

### ISSUE THREAD

**Issue by wradstok** [Accenture/AmpliGraph#199]
**Background and Context**
Recently, I got an email from my local sysadmin asking why I was creating ~300 threads for every script I was running. Apparently the load was slowing down other users, which was not considered a very nice thing to do :).

It would be nice if there was a way to limit the number of threads that ampligraph (or tensorflow?) uses when fitting a model. I already tried setting the tensorflow `intra_op_parallelism_threads` and `inter_op_parallelism_threads` settings, but that did not make a difference.

**Comment by sumitpai** [comment]
Are you running tensorflow-gpu or cpu only version?

**Comment by wradstok** [comment]
I'm running the CPU only version

Op di 16 jun. 2020 om 10:15 schreef sumitpai <notifications@github.com>:

**Comment by sumitpai** [comment]
did you pip install ampligraph or did you install from sources? If from sources, can you try setting the following in the constructor:
```
self.tf_config = tf.ConfigProto(allow_soft_placement=True)
# Add these two lines in the constructor of Embedding Models.py
self.tf_config.intra_op_parallelism_threads = 1
self.tf_config.inter_op_parallelism_threads = 1
```

**Comment by wradstok** [comment]
Seems to be working, made the modification you listed and now CPU usage stays pegged at 100% as expected.

Thanks for the help!

**Comment by sumitpai** [comment]
sorry for the delay in answering.
