### ISSUE TITLE
TypeError: '<' not supported between instances of 'float' and 'str' 

### ISSUE THREAD

**Issue by Wickky** [Accenture/AmpliGraph#201]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-867979a65e4a> in <module>
----> 1 entities = np.unique(np.concatenate([X[:, 0], X[:, 1]]))
      2 entities

<__array_function__ internals> in unique(*args, **kwargs)

~/anaconda3/envs/ampligraph/lib/python3.7/site-packages/numpy/lib/arraysetops.py in unique(ar, return_index, return_inverse, return_counts, axis)
    261     ar = np.asanyarray(ar)
    262     if axis is None:
--> 263         ret = _unique1d(ar, return_index, return_inverse, return_counts)
    264         return _unpack_tuple(ret)
    265 

~/anaconda3/envs/ampligraph/lib/python3.7/site-packages/numpy/lib/arraysetops.py in _unique1d(ar, return_index, return_inverse, return_counts)
    309         aux = ar[perm]
    310     else:
--> 311         ar.sort()
    312         aux = ar
    313     mask = np.empty(aux.shape, dtype=np.bool_)

TypeError: '<' not supported between instances of 'float' and 'str'

I got the above error when I have int type in my entities (sub or objs).  eg. 2010, 2019

**Comment by wradstok** [comment]
Hi Wickky,

I just tried the following data set where I put random integers at positions in the name. I even put one name as just an integer and it seemed to work. 
```
<a>21	<b>[-431]	<c_2009>
3000	<g>[1790-2017]	<f[2100]>
3000	<g>[1790-2017]	<c_2009>
<f[2100]>	<b>[-431]	<a>21
```

However, I do get that error when I seperate my data set by spaces instead of tabs. Could you check whether this is the case, or else upload (a part of) the data set you are trying to use?

**Comment by sumitpai** [comment]
can you try casting the dataset to string:

```
dataset = dataset.astype(np.str)
```
