### ISSUE TITLE
Train test split error

### ISSUE THREAD

**Issue by romass12** [Accenture/AmpliGraph#213]
### Description
I have made a new dataset on which I want to train ComplEX model
### Actual Behavior
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-64-1572e435727c> in <module>
      4 print(num_test)
      5 data = {}
----> 6 data['train'], data['test'] = train_test_split_no_unseen(X, test_size=num_test)

~/anaconda3/envs/ampligraph/lib/python3.7/site-packages/ampligraph/evaluation/protocol.py in train_test_split_no_unseen(X, test_size, seed, allow_duplication)
    136                                 "Change seed values, or set test_size to a smaller value.")
    137             else:
--> 138                 raise Exception("Cannot create a test split of the desired size. "
    139                                 "Some entities will not occur in both training and test set. "
    140                                 "Set allow_duplication=True, or "

Exception: Cannot create a test split of the desired size. Some entities will not occur in both training and test set. Set allow_duplication=True, or change seed values, or set test_size to a smaller value.

### Expected Behavior
It should have produced splits

**Comment by sumitpai** [comment]
Can you tell me the number of unique subjects, objects and entities in your dataset and the size of test set that you are trying to create?

The above function tries to creates splits such that the test set contains only the enitites that are "seen" during training. However, it looks like it is unable to do so. One of the following should solve your problem (prioritise in the order described below):
- Change the seed. OR 
- Reduce the test set size OR 
- set the `allow_duplication` to true (this may add a few training triples in the test set).
