### ISSUE TITLE
Tensorboard: No dashboards are active for the current data set

### ISSUE THREAD

**Issue by yuis-ice** [Accenture/AmpliGraph#221]
### Description

I was seeing a tutorial here [Getting Started with AmpliGraph — AmpliGraph 1.3.2 documentation](https://docs.ampligraph.org/en/1.3.2/tutorials/AmpliGraphBasicsTutorial.html)

In the almost end of the tutorial it mentioned visualization with Tensorboard, it said: 

> To visualize the embeddings in Tensorboard, run the following from your command line inside AmpliGraph/tutorials:

> tensorboard --logdir=./visualizations

but, the tensorboard url http://192.168.0.183:6006/ on the browser, tensorboard said: "No dashboards are active for the current data set"

I have done installation using conda with here [Installation — AmpliGraph 1.3.2 documentation](https://docs.ampligraph.org/en/1.3.2/install.html)

I have done the tutorial as well, except the tensorboard visualization part. 

### Actual Behavior

the tensorboard url http://192.168.0.183:6006/ on the browser, tensorboard said: "No dashboards are active for the current data set"

### Expected Behavior

Tensorboard should render some content on the browser

**Comment by sumitpai** [comment]
The problem is in the documentation.

When you run :
```
create_tensorboard_visualizations(model, 'GoT_embeddings')
```

it will create a folder called `GoT_embeddings` which needs to be passed as argument to tensorboard command

So the following should work,

```
tensorboard --logdir=./GoT_embeddings
```
