### ISSUE TITLE
discover_facts produces an error

### ISSUE THREAD

**Issue by laleye** [Accenture/AmpliGraph#224]
### Description
I tried to use discover_facts function with a pretrained model and I got the following error: 

### Actual Behavior
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-13-01f1f3fad14b> in <module>
----> 1 discover_facts(X, md.model, top_n=3, max_candidates=20000, strategy='entity_frequency', target_rel='ALLIED_WITH', seed=42)

~/.virtualenvs/viz/lib/python3.6/site-packages/ampligraph/discovery/discovery.py in discover_facts(X, model, top_n, strategy, max_candidates, target_rel, seed)
    113         raise ValueError(msg)
    114 
--> 115     if not model.is_fitted_on(X):
    116         msg = 'Model might not be fitted on this data.'
    117         logger.warning(msg)

~/.virtualenvs/viz/lib/python3.6/site-packages/ampligraph/latent_features/models/EmbeddingModel.py in is_fitted_on(self, X)
   1543             raise RuntimeError(msg)
   1544 
-> 1545         unique_ent = np.unique(np.concatenate((X[:, 0], X[:, 2])))
   1546         unique_rel = np.unique(X[:, 1])
   1547 

~/.virtualenvs/viz/lib/python3.6/site-packages/pandas/core/frame.py in __getitem__(self, key)
   2904             if self.columns.nlevels > 1:
   2905                 return self._getitem_multilevel(key)
-> 2906             indexer = self.columns.get_loc(key)
   2907             if is_integer(indexer):
   2908                 indexer = [indexer]

~/.virtualenvs/viz/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_loc(self, key, method, tolerance)
   2896             casted_key = self._maybe_cast_indexer(key)
   2897             try:
-> 2898                 return self._engine.get_loc(casted_key)
   2899             except KeyError as err:
   2900                 raise KeyError(key) from err

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

TypeError: '(slice(None, None, None), 0)' is an invalid key

### Steps to Reproduce
1. I pretrained a ComplEx model
2. I used restore_model to load it
3. Apply discovery_fact function

**Comment by sumitpai** [comment]
X must be a numpy array of size (n, 3) and not a dataframe. Can you check if you are passing X in the correct format?

**Comment by sumitpai** [comment]
Also make sure X is same as the dataset used for training the model. (i.e. the training set)

**Comment by laleye** [comment]
I converted it to nupmy and it works. 
Thanks
