### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by ziwli** [Accenture/AmpliGraph#225]
hello, when I run the example code of 'save and restore model', I failed. There exists an error 'from tensorflow.contrib.tensorboard.plugins import projector
ModuleNotFoundError: No module named 'tensorflow.contrib''. Can I ask how to deal with this?

**Comment by sumitpai** [comment]
you must install tensorflow 1.13 onwards to use ampligraph

if you have a GPU, then do the following:
`pip install tensorflow-gpu==1.13`

if you do not have a gpu:
`pip install tensorflow==1.13`

**Comment by lukostaz** [comment]
@ziwli , [check this out](https://docs.ampligraph.org/en/1.3.2/install.html#install-tensorflow) to install the most updated version of tf for ampligraph.

**Comment by ziwli** [comment]
Dear Sir or Madam,

      I have installed the tensowflow and install again according to the
website tutorial, but still could not work. The error is same....

**Comment by ziwli** [comment]
Dear sir or madam,

     I think I have found the issue, that when I install tensorflow
1.0, tensorflow
is wrong 'ModuleNotFoundError: No module named 'tensorflow''; when I
install tensorflow 2.0, tensorflow.contrib(in model_utils) is wrong.... I
don't know if someone has the problem like me. I also re-install all the
env according to your tutorial. But there always something wrong with
that....I use pycharm

Best wishes
Ziwei Li

**Comment by lukostaz** [comment]
@ziwli the latest stable release of ampligraph (1.3.2) runs on tensorflow 1.x. 
It is not (yet) compatible with tf 2.x.

To install the correct version of tf: 

```
pip install "tensorflow>=1.15.2,<2.0"
```
or 
```
conda install tensorflow'>=1.15.2,<2.0.0'
```
