### ISSUE TITLE
Edge Weights and Node Features

### ISSUE THREAD

**Issue by egealpay** [Accenture/AmpliGraph#227]
Is it possible to assign weights to edges and feature vector to nodes?

**Comment by sumitpai** [comment]
As of now, we have no specific approach to do this. We may plan to add some support in the future.

**Comment by lukostaz** [comment]
@egealpay for edge weights, you may want to check out the [latest 1.4.0 release.](http://docs.ampligraph.org/)

- [Support for numeric edge literals](https://docs.ampligraph.org/en/1.4.0/ampligraph.latent_features.html#edge-literals).
- [arXived paper ](https://arxiv.org/abs/2105.08683)
