### ISSUE TITLE
how to check the embedding weights?

### ISSUE THREAD

**Issue by lzw950905** [Accenture/AmpliGraph#229]
Dear Sir or Madam,

       after training the results, I want to save the model, but could not find the entity and relation weights. I thought it is model.trained_model_parameters, but it seems not. Could you tell me how to check the entity and relation weights? (trained weights)

**Comment by lukostaz** [comment]
Hello @lzw950905 .
The trained weights are indeed the embeddings.
You can save and restore models (i.e. saving and restoring embeddings) with the [`save_model()` and `restore_model`](https://docs.ampligraph.org/en/1.3.2/ampligraph.utils.html#saving-restoring-models) APIs.
