### ISSUE TITLE
Implement nuclear 3 norm

### ISSUE THREAD

**Issue by lukostaz** [Accenture/AmpliGraph#23]
**Description**
Implement Nuclear 3 norm as presented by [Lacroix2018](https://arxiv.org/abs/1806.07297).

See section 4 of the paper (in particular 4.2)

![image-2019-02-06-11-26-00-421](https://user-images.githubusercontent.com/1206732/53949758-a5bd7200-40c2-11e9-9744-19e86b76867e.png)

**Comment by tabacof** [comment]
Solved by #107. While the results of the original paper could not be reproduced exactly, we got the best results so far for the two hardest datasets using the nuclear 3-norm regularisation (plus multiclass NLL).
