### ISSUE TITLE
Using K-Means with embeddings generated by ComplEx in the example "Clustering and projectings embeddings into 2D space"

### ISSUE THREAD

**Issue by juarezsacenti** [Accenture/AmpliGraph#232]
Hi Ampligraph team and collaborators,

### Description
The example "Clustering and projectings embeddings into 2D space" applies k-means to clusterize teams using the embeddings generated by ComplEx. The euclidean distance is the default function of k-means and I believe that it isn't support complex numbers.

### Actual Behavior
No error or warning occurs because the embedding generated by ComplEx represents the real and imaginary components of complex numbers with float32. However, I'm not sure if the algebraic semantics are equivalents or if the euclidean distance is adequate. **Would you please explain to me if is it wrong to combine ComplEx with k-means in this way?**

### Expected Behavior
A warning in the description of this example with this explanation would be very appreciated for future users.

### Steps to Reproduce
I run the example and no error occurs. The usage of euclidean distance with complex numbers was already discussed in the internet. The following example shows that an error occurs when a nparray of complex numbers is given as input of sklearn.euclidean_distance.

>>> from numpy import *
>>> A = zeros((4), dtype=complex)
>>> A
array([0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])
>>> for i in range(0,len(A)):
...     A[i] = random.rand(1) + random.rand(1)*1j
...
>>> A
array([0.25713601+0.44146511j, 0.84433253+0.36501779j,
       0.6893429 +0.26250964j, 0.03404544+0.43901864j])
>>> B = zeros((4), dtype=complex)
>>> for i in range(0,len(B)):
...     B[i] = random.rand(1) + random.rand(1)*1j
...
>>> B
array([0.26915248+0.39955162j, 0.74526646+0.05775906j,
       0.38402725+0.42247887j, 0.36050013+0.61588844j])
>>> euclidean_distances(A, B)
Traceback (most recent call last):
  File "~/lib/python3.6/site-packages/sklearn/utils/validation.py", line 616, in check_array
    array = np.asarray(array, order=order, dtype=dtype)
  File "~/lib/python3.6/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
numpy.ComplexWarning: Casting complex values to real discards the imaginary part

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/lib/python3.6/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "~/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 272, in euclidean_distances
    X, Y = check_pairwise_arrays(X, Y)
  File "~/lib/python3.6/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "~/lib/python3.6/site-packages/sklearn/metrics/pairwise.py", line 148, in check_pairwise_arrays
    estimator=estimator)
  File "~/lib/python3.6/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "~/lib/python3.6/site-packages/sklearn/utils/validation.py", line 619, in check_array
    "{}\n".format(array)) from complex_warning
ValueError: Complex data not supported
[0.25713601+0.44146511j 0.84433253+0.36501779j 0.6893429 +0.26250964j
 0.03404544+0.43901864j]

**Comment by sumitpai** [comment]
@juarezsacenti I will have a look at this

**Comment by juarezsacenti** [comment]
Thank you, @sumitpai 
I will be waiting for your opinion about it.

**Comment by sumitpai** [comment]
The distance between 2 complex points `x+yi` and `a+bi` is : 
![image](https://user-images.githubusercontent.com/39597669/118314892-b1035800-b4ec-11eb-975c-fb9ce3d42536.png)

The same can be extended to higher dims. 

The embedding vector itself is represented in our code as a numpy array of type float32. Since we do not explicitly use a+ij format but just a concatenation of real and imaginary part in a single float32 numpy array, the euclidean distance can handle it and computes the distance as shown in the above formula.
