### ISSUE TITLE
Implement multi-class log-loss

### ISSUE THREAD

**Issue by lukostaz** [Accenture/AmpliGraph#24]
**Description**

Implement multi-class log-loss as presented by [Lacroix2018](https://arxiv.org/abs/1806.07297).

In section 6.2 (see screenshot below) they claim multi-class log-loss can be responsible for better results compared to our current binomial nll loss:

![image](https://user-images.githubusercontent.com/1206732/53949863-da312e00-40c2-11e9-9ae0-815ac4b454f6.png)
![image](https://user-images.githubusercontent.com/1206732/53949883-e4532c80-40c2-11e9-9bf5-8c26d652c023.png)

This is similar to [Kadlec2017](https://arxiv.org/pdf/1705.10744), where they use a sampled multi-class log loss that seems to perform better than ComplEx's current binomial nll loss (see also #22).

From [Kadlec2017](https://arxiv.org/pdf/1705.10744):
![image](https://user-images.githubusercontent.com/1206732/53950697-a9ea8f00-40c4-11e9-90d4-b5f551f593c4.png)

And indeed Kadlec2017 uses the loss defined by [Toutanova2015](http://www.aclweb.org/anthology/W15-4007), that defines the loss as (section 3.3):
![image](https://user-images.githubusercontent.com/1206732/53951715-03ec5400-40c7-11e9-9ad2-16c3c09a549d.png)
![image](https://user-images.githubusercontent.com/1206732/53951734-0b136200-40c7-11e9-8924-c91a1e88e215.png)

**Comment by sumitpai** [comment]
Observation: Performance (MRR) better than nll/pairwise loss over FB15k but does not beat self_adversarial. This was tested with limited parameter combinations. Need extensive hyperparameter search to compare with self_adversarial.
