### ISSUE TITLE
Implement alternative ranking evaluation protocols

### ISSUE THREAD

**Issue by lukostaz** [Accenture/AmpliGraph#25]
**Background**

Literature adopts different interpretations of the ranking evaluation protocol. We must implement alternative protocols, to be enabled with a flag in the evaluation function, to get fair comparisons of results.

**Description**

Protocols to implement:

- Trouillon16 (ComplEx paper): ranks each positive against corruptions of head and tail _together_. (current implemented version)
- ConvE, RotatE: corrupt head and tail _separately_

Implement the evaluation strategy described by RotatE and ConvE.
This may imply also revisiting the metric implementations (MRR, MR, Hits@N).

From the ConvE paper:

![image](https://user-images.githubusercontent.com/1206732/53966838-eda4bf00-40eb-11e9-8345-c6d9561aab67.png)

See also [RotatE reference implementation ](https://github.com/DeepGraphLearning/KnowledgeGraphEmbedding) for clues.

**Comment by sumitpai** [comment]
Add direct support in evaluation rather than indirect
