### ISSUE TITLE
Resolve warnings in code to future proof module.

### ISSUE THREAD

**Issue by rorymcgrath** [Accenture/AmpliGraph#26]
**Background and Context**
Current when running tests there are 156 warnings generated.
These warnings are due to the use of deprecated methods or future warnings about methods that will be removed in the next iteration of pandas.
To help support future versions we should resolve these issues.

**Description**
Warnings need to be resolved or handled to avoid future updates of dependencies.

**Comment by tabacof** [comment]
@rorymcgrath Running the test suite (with the skips) on a Linux machine gives me 29 warnings, however all of them seem to be outside our control. They are mostly internal Tensorflows warnings. Maybe I am missing something, but is this issue still relevant?

**Comment by rorymcgrath** [comment]
Initially there were over 150 warnings when running unit tests. If any remaining warnings are outside the control of Ampligraph or the user they should be suppressed.
