### ISSUE TITLE
Migrate to tensor flow 2 

### ISSUE THREAD

**Issue by rdelaguila** [Accenture/AmpliGraph#262]
Some environments and libraries  are now working with tf 2. It is worth to upgrade Ampligraph to run over TF 2.X as described in https://www.tensorflow.org/guide/migrate/migrate_tf2

**Comment by sumitpai** [comment]
We are on it and it will be released soon :)

**Comment by ChrisDelClea** [comment]
+1

**Comment by lukostaz** [comment]
@rdelaguila , @ChrisDelClea better now than never ;-)
- [Rel 2.0.0](https://github.com/Accenture/AmpliGraph/releases/tag/2.0.0)  
- [Changelog](https://docs.ampligraph.org/en/latest/changelog.html)
- [Tutorial](https://docs.ampligraph.org/en/latest/tutorials.html)

**Comment by rdelaguila** [comment]
wow!!
