### ISSUE TITLE
https://github.com/Accenture/AmpliGraph/blob/d4bf44559cb7178039f21203780be4eb946ea4eb/experiments/IJCAI-21/experiments.py#L12

### ISSUE THREAD

**Issue by Diison** [Accenture/AmpliGraph#263]
There is an obvious bug, how can you get the experimental results in your IJCAI paper with this wrong code?

def compare_vanilla_focusE_models(dataset, model_name, vanilla_params, focusE_params):
    if dataset == 'onet20k':
        X = load_onet20k()
    elif dataset == 'ppi5k':
        X = load_onet20k()
    elif dataset == 'nl27k':
        X = load_onet20k()
    elif dataset == 'cn15k':
        X = load_onet20k()
    else:
        raise ValueError('Invalid Dataset name!')

**Comment by sumitpai** [comment]
Hi, Sorry about that. It is a copy-paste issue - while compiling the snippets that were spread across in different files. You can modify the loaders, and you would get the results in the paper. We will update this in the next release.
