### ISSUE TITLE
AttributeEerro while running the code

### ISSUE THREAD

**Issue by Gautamshahi** [Accenture/AmpliGraph#272]
### Description
Hello, I am trying to run the tutorial code from Amlipgraph, but I am not able to do it, because there is an error. Did somebody face the same? How to solve it?

### Actual Behavior
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/3966230/230748682-9b8f6f65-3cc2-42db-a77f-e7d45a4e8a99.png">

**Comment by albernar** [comment]
Pass a np.array to the predict method for a quick workaround. Extending support for list of lists in the API as well
