### ISSUE TITLE
AttributeError: 'ScoringBasedEmbeddingModel' object has no attribute '_reset_compile_cache' 

### ISSUE THREAD

**Issue by cobycloud** [Accenture/AmpliGraph#280]
AttributeError: 'ScoringBasedEmbeddingModel' object has no attribute '_reset_compile_cache'

**Comment by cobycloud** [comment]
ScoringBasedEmbeddingModel.compile() uses self._reset_compile_cache() within, which triggers this issue.

**Comment by ddofer** [comment]
Same issue - I tried running the default example (https://docs.ampligraph.org/en/latest/examples.html) and it fails on this

**Comment by bpsut** [comment]
Just got this issue too, anyone already have a work around?

**Comment by sumitpai** [comment]
Downgrade the version of tensorflow to 2.12 and it should work.

**Comment by bpsut** [comment]
Awesome, thank you, that worked perfectly.

**Comment by GrozniyMax** [comment]
tensorflow 2.12 was removed from pip
What to do now?

**Comment by SamSaver** [comment]
@GrozniyMax Were you able to solve this issue? I am also facing the same issue.
