### ISSUE TITLE
Question: Is it possible to integrate two embedding model?

### ISSUE THREAD

**Issue by anonimoustt** [Accenture/AmpliGraph#283]
**Background and Context**
Integrating two or more embedding models
**Description**
Hi, is it possible to ingrate two different embedding models? Let us say model1 = ScoringBasedEmbeddingModel(k=5, eta=1, scoring_type='TransE'), and model 2= ScoringBasedEmbeddingModel(k=5, eta=1, scoring_type='RotatE'). Is there a pipeline to combine these two models in Ampligraph?

**Comment by albernar** [comment]
Hello, as far as I know there is no work that tried to integrate the two embeddings into a unique one, so there is no implementation of it on AmpliGraph. 

A straightforward way of doing it could be creating a consensus model averaging the rank predictions for the models you are interested into and reorder them, but I wouldn't know whether that would work well in practice.
