### ISSUE TITLE
Execution Error in Tutorial (docs/tutorials/AmpliGraphBasicsTutorial.ipynb)

### ISSUE THREAD

**Issue by kinue00** [Accenture/AmpliGraph#288]
### Description
I was trying to go through the tutorial with Game of Throne dataset as indicated in title but I got an error while initiating the link prediction model (ComplEx).

### Actual Behavior
I followed the exact code, no modification. I have tried for ampligraph==2.0.0 and 2.1.0, the results were the same.
![Screenshot 2024-12-01 at 17 01 35](https://github.com/user-attachments/assets/0a0e1873-c57b-4262-87ec-ff18c12d3cba)
The error looks like this.

The version in tuto is actually 2.0-dev, I also tried for the latest dev version but there was still the same error.
Can somebody help me?

**Comment by albernar** [comment]
It's most likely depending on the wrong Tensorflow version. You should install tensorflow==2.10 (on Colab, execute a cell `!pip install tensorflow==2.10`). We are working to extend the support to more up-to-date versions.
Feel free to re-open the issue if not solved.

**Comment by kinue00** [comment]
> It's most likely depending on the wrong Tensorflow version. You should install tensorflow==2.10 (on Colab, execute a cell `!pip install tensorflow==2.10`). We are working to extend the support to more up-to-date versions. Feel free to re-open the issue if not solved.

Thank you sir, problem solved.
