### ISSUE TITLE
Add MD5 checksum for datasets

### ISSUE THREAD

**Issue by lukostaz** [Accenture/AmpliGraph#47]
**Description**
Each dataset loader should have an argument `check_MD5` (set to `False` by default) that performs MD5 checksum of the downloaded dataset.

**Comment by rorymcgrath** [comment]
Do the md5 checksums already exist for these database provided by the original papers or will we be generating them ourselves?

Currently we don't seem to have them.

If we are using them to validate that the datasets are the same as used in the referenced papers we need to their original md5 checksums.

If we are using them to validate that the download was not corrupted, generating them ourselves will be fine.

**Comment by lukostaz** [comment]
Original datasets do not come with a checksum, unfortunately.
We will have to generate checksums from a version we download from their original URLs:

- wn18, fb15k:  https://www.hds.utc.fr/everest/doku.php?id=en:transe [DEAD LINK - compute the MD5 stright from our datasets.]
- fb15k-237: https://www.microsoft.com/en-us/download/details.aspx?id=52312
- wn18RR: DettmersMS018 https://github.com/TimDettmers/ConvE/blob/master/WN18RR.tar.gz
- YAGO3-10  https://github.com/TimDettmers/ConvE/blob/master/YAGO3-10.tar.gz
- WN11 & FB13: https://cs.stanford.edu/people/danqi/data/nips13-dataset.tar.bz2

**Comment by lukostaz** [comment]
Just noticed the `check_md5hash` argument is not documented in docstrings. 
Can you please amend?
