### ISSUE TITLE
Cannot evaluate performance for Random Baseline model

### ISSUE THREAD

**Issue by PeruBhardwaj** [Accenture/AmpliGraph#51]
### Description
The function evaluate_performance here does not work for Random Baseline model- https://github.com/Accenture/AmpliGraph/blob/e7b496d7e266afebaa46b2e36bd6c2ddee565feb/ampligraph/evaluation/protocol.py#L317

### Actual Behavior
<img width="1116" alt="Screen Shot 2019-03-14 at 11 31 13" src="https://user-images.githubusercontent.com/16183384/54353758-bfbffd00-464c-11e9-9273-60b13d355c96.png">

### Expected Behavior
The function should return an array of ranks with size equal to the number of triples

### Steps to Reproduce

<img width="1100" alt="Screen Shot 2019-03-14 at 11 34 09" src="https://user-images.githubusercontent.com/16183384/54353906-234a2a80-464d-11e9-815a-7e46f7ca427a.png">

**Comment by PeruBhardwaj** [comment]
I still get this error from evaluate_performance (version is 1.0-dev)

<img width="1117" alt="Screen Shot 2019-03-15 at 14 28 05" src="https://user-images.githubusercontent.com/16183384/54438468-95df0700-472e-11e9-80b3-e8cb9194cd8d.png">

**Comment by sumitpai** [comment]
Have you pulled the latest commit from Ampligraph? I am not able to reproduce this error. 
<img width="516" alt="Screen Shot 2019-03-15 at 14 53 12" src="https://user-images.githubusercontent.com/39597669/54440187-23702600-4732-11e9-9a73-c8af23d23693.png">

**Comment by PeruBhardwaj** [comment]
I pulled the commit yesterday. Should I do it again?

<img width="1083" alt="Screen Shot 2019-03-15 at 14 57 03" src="https://user-images.githubusercontent.com/16183384/54440497-bd37d300-4732-11e9-90e7-8bb6a04cb439.png">
<img width="1102" alt="Screen Shot 2019-03-15 at 14 59 28" src="https://user-images.githubusercontent.com/16183384/54440615-f708d980-4732-11e9-9153-7582aa85095c.png">

<img width="1106" alt="Screen Shot 2019-03-15 at 15 03 28" src="https://user-images.githubusercontent.com/16183384/54440928-89a97880-4733-11e9-91f7-0b6464530aa9.png">

**Comment by sumitpai** [comment]
Yes. It was fixed in commit 13cd29bd8aa26bbc82a270d27e3b86f918cd30e3 yesterday. So better to pull all the changes so that the local copy has all the fixes.

**Comment by PeruBhardwaj** [comment]
Works now. Thanks!
