### ISSUE TITLE
Integrate dataset loaders documentation

### ISSUE THREAD

**Issue by lukostaz** [Accenture/AmpliGraph#55]
**Description**
- Add missing dostrings (WN11, FB13)
- Add biblio references for each dataset (see slack for list)
- Add orginal URL from which dataset has been downloaded
- Update `installation.md`, dataset section.

**Comment by rorymcgrath** [comment]
Original url have been added to `ampligraph.datasets.html`

**Comment by rorymcgrath** [comment]
Each dataset is referenced in the bib file.
