### ISSUE TITLE
Update the models default hyperparams with optimal default values

### ISSUE THREAD

**Issue by lukostaz** [Accenture/AmpliGraph#58]
**Description**

The default hyperparams used to initialize a model should be updated to values that we consider the most performing for a generic dataset, and that strike an **acceptable predictive power/training time, and predictive power/memory footprint trade off** (i.e. no `epochs=2000` or `eta=200`).

For example: 

```
ComplEx(k=100, eta=2, epochs=100, batches_count=100, seed=0, embedding_model_params={}, optimizer='adagrad', optimizer_params={'lr': 0.1}, loss='nll', loss_params={}, regularizer=None, regularizer_params={}, model_checkpoint_path='saved_model/', verbose=False, **kwargs)
```

Perhaps `optimizer='adam'`, etc.
A good starting point is looking at the best combinations of hyper-params we used to replicate SoA results.

**Comment by sumitpai** [comment]
Fixed in commit 398add2e29bc65127707474a79e38993c5f39b84
