### ISSUE TITLE
Undefined name ‘embs_labels’ in test.py

### ISSUE THREAD

**Issue by cclauss** [Accenture/AmpliGraph#65]
https://github.com/Accenture/AmpliGraph/search?q=embs_labels

**Comment by chanlevan** [comment]
Hi @cclauss Thanks for opening this issue. 

According to what I have seen in your test code, the embs_labels has not been declared before. 

To get the embeddings, you need to fit the it first, as you did your test.py file. Second, you should assign the embs_labels  with the interested embedding labels and put to the get_embeddings API. 

For instance, we exemplify the get_embeddings in http://docs.ampligraph.org/en/1.0.1/examples.html#get-the-embeddings. After we fitted the dataset, we extract the embedding by sending an entity list ['f', 'e']  to the get_embeddings API. In this case, embs_labels = ['f', 'e']

Hope this help.

**Comment by chanlevan** [comment]
This file was there by mistake.
It has been removed.
