### ISSUE TITLE
Define a model name for saved models

### ISSUE THREAD

**Issue by pyvandenbussche** [Accenture/AmpliGraph#71]
**Background and Context**
Currently, using the `save_model()` function in `model_utils`, will always result in a pickled file named 'model.pickle'. This is very limiting when you perform multiple experiments. 

**Description**
Why not adding a new argument to the function with a custom made name? The current name can be used as default but I would rather suggest a name with the creation time included to avoid loosing previously saved models and to give more context to users who did not specify a name.

**Comment by chanlevan** [comment]
@pyvandenbussche Thanks for your helpful suggestion. The code has been updated. Now the model can be saved with customised name or with default option with timestamp.
