### ISSUE TITLE
Add unit test cases

### ISSUE THREAD

**Issue by sumitpai** [Accenture/AmpliGraph#75]
**Background and Context**
We need to add more test cases so that the code coverage is better.
**Description**

**Comment by sumitpai** [comment]
915fe86514dc59c2b0e7b65d310db44d26757bdc and a4408e7d9a27cb7610de231320f2999ff981a014 adds test cases for covering evaluate performance (with and without filtering)

**Comment by lukostaz** [comment]
Closing, as issue will be superseded by finer granularity tickets.
