### ISSUE TITLE
Verbose mode defined in parameter grid as well as select_best_model_ranking

### ISSUE THREAD

**Issue by NicholasMcCarthy** [Accenture/AmpliGraph#79]
This may just be a documentation issue:

The param_grid dict in docstring for select_best_model_ranking includes "verbose=True". This is also a parameter passed to select_best_model_ranking directly. 

It looks like the verbose parameter is used in most cases, but as the dict of model params is instantiated in the class:

        model = model_class(**model_params)

there may be some unintended effects if verbose=True in the param_grid dict, and verbose=False in the parameter passed to select_best_model_ranking.

**Comment by tabacof** [comment]
Solved by https://github.com/Accenture/AmpliGraph/pull/108/
