### ISSUE TITLE
Inconsistent use of 'X' argument in some functions

### ISSUE THREAD

**Issue by NicholasMcCarthy** [Accenture/AmpliGraph#80]
The `X` argument is used to indicate a np.array, or a dict of np.array, depending on the function. 

Examples: 

`ampligraph.evaluation.evaluate_performance `

`X` argument is a np.array (e.g. data['test']) 

`ampligraph.evaluation.select_best_model_ranking`

`X` argument is a dict of np.arrays (e.g. data, with 'train', 'test', 'valid' keys)

**Fix** 

Although it adds to the (already quite long) list of arguments for select_best_model_ranking, specifying each set separately might be less confusing:

e.g.
`select_best_model_ranking(X_train=data['train'], X_test=data['test'], X_valid=data['valid'] .. ) `

**Comment by tabacof** [comment]
Solved by this commit: https://github.com/Accenture/AmpliGraph/commit/6e4a22ab67876c62295686efd2f59311b7bf13bc

I could not find anywhere else in the code where this issue happens, besides the aforementioned `select_best_model_ranking`.

@NicholasMcCarthy @lukostaz do you agree with this solution?
