### ISSUE TITLE
save_model with model_name_path=None fails

### ISSUE THREAD

**Issue by NicholasMcCarthy** [Accenture/AmpliGraph#83]
If no model_name_path specified the model name generated from a timestamp which includes ':' 

model_name_path = DEFAULT_MODEL_NAMES.format(strftime("%Y_%m_%d_%H:%M:%S", gmtime()))

this gives:

OSError: [Errno 22] Invalid argument: '2019_04_15_16:44:04.model.pkl'

*Fix*: 

Remove the ':' from strftime format string. 

e.g.

%Y_%m_%d_%H:%M:%S -> %Y_%m_%d-%H_%M_%S

**Comment by chanlevan** [comment]
Could you merge it to develop before closing?
