### ISSUE TITLE
Embeddings TSV output

### ISSUE THREAD

**Issue by NicholasMcCarthy** [Accenture/AmpliGraph#86]
The embeddings projector found here: https://projector.tensorflow.org

can take a TSV file of embeddings as input. 

We should implement TSV output so that users can upload to this service to visualize, rather than running tensorboard locally.

**Comment by NicholasMcCarthy** [comment]
Implemented in feature/86 branch, closing.

**Comment by lukostaz** [comment]
@NicholasMcCarthy I will merge `create_tensorboard_projector_files()` and `create_tensorboard_visualizations()` in a single API, to make things simpler.

**Comment by lukostaz** [comment]
Fixed in `7efea08`. Closing.
