### ISSUE TITLE
Restore model and Continue trainning

### ISSUE THREAD

**Issue by Sissie1122** [Accenture/AmpliGraph#88]
**Background and Context**
Could you add a feature which allow the model to be restored and trained based on previous training result ?
**Description**

**Comment by rorymcgrath** [comment]
Hi @Sissie1122 
To follow up, would this requested feature be:

> Given a model is going to take 10 hours to train you would like to pause and resume the training such that you could train for 5 hours, pause, resume for 2 hours, pause and then resume for 3 hours.

or would it be:

> Given you have already trained a model on some data, you would like to use this previously trained model as an initial point to bootstrap learning on new data?

**Comment by Sissie1122** [comment]
Actually, using previously trained result as initialization is enough to suit my needs. And I also hope the training loss could be printed or visualized in tensorboard, which will help the user to adjust parameter. Thank you! @chanlevan
