### ISSUE TITLE
Variations in Knowledge Graph

### ISSUE THREAD

**Issue by idigitopia** [Accenture/AmpliGraph#96]
**Background and Context**
I am currently working on a class project regarding structural/content variation in Knowledge graphs and its effect on algorithms running on top of it. 

I was wondering if anyone has looked into this. I could not find much literature on this on the internet.

Could not thank all the developers for the awesome codebase! 

**Description**
Ideally, I am thinking of adding something like 
transformation_func = Tranformation(dataset_constraints)
transform_dataset( dataset, transformation_func)

Any suggestion on how and where I should add this to the repository would be wonderful.

Thanks!

**Comment by lukostaz** [comment]
Ideally, this is something that could go in the `datasets` submodule. 

We'll need some additional info, though.
Which kind of transformation are you thinking about?
Can you please elaborate in more detail?
