### ISSUE TITLE
Fix PEP8 violations

### ISSUE THREAD

**Issue by tabacof** [Accenture/AmpliGraph#97]
**Background and Context**
PEP8 is the standard style guide for Python: https://www.python.org/dev/peps/pep-0008/

According to `flake8`, AmpliGraph currently has *1254* violations, mostly related to long lines.

An IDE like PyCharm will mark the PEP8 violations as warnings.

**Description**
There are three sub-tasks:
1. Decide which standard to follow. My suggestion would be for the standard flake8.
2. Fix the code violations.
3. [Optional] Add the flake8 check to the Jenkins script to make the build fail if there is any violation.

**Comment by davidwilson3** [comment]
I'd like to take a stab at this if it's still up for grabs.

**Comment by tabacof** [comment]
Solved by this commit: https://github.com/Accenture/AmpliGraph/commit/7991c2cbdc34a59f0e325ee9b30a2d62a91eb021

**Important:**

Adding flake8 to the Jenkins build script to prevent future violations. 

The flake8 command has been customized with two changes:
1. Increasing the line length to 120 instead of 80
2. Removing some whitespace warnings

Both changes make the linting more similar to the default PyCharm configuration.
